server:
  port: 8080

spring:
  application:
    name: QR Attendance

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  datasource:
    url: jdbc:postgresql://localhost:5434/qr_attendance
    username: user
    password: pass

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/UniversityAttendance

  data:
    redis:
      host: localhost
      port: 6379

app:
  token:
    ttl-seconds: 900

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
